### ISSUE TITLE
Does the scheduler persist?

### ISSUE THREAD

**Issue by prakashraman** [procyon-projects/chrono#3]
I am looking for a task scheduler which can execute tasks in the future. And Chrono seems pretty amazing! and close to my need.

However, I'd like to know if there is a backing store? And does the schedule tasks persist through restarts as well?

Thanks

**Comment by burakkoken** [comment]
Hi, first of all, thanks for your feedback.

Unfortunately, chrono does not store your scheduled tasks. If you don't schedule your tasks dynamically by the user inputs, you can try to schedule your tasks in **init** method so that even if your program restarts, your task will be scheduled at the startup.

If you have any further questions, please free to ask.

**Comment by burakkoken** [comment]
This issue is closed due to inactivity
